/**
 * Auto-generated by gen-assets.js
 * Source : /Users/ayobami/code/RiseAcademy/chatme/src/assets/svgs/icon
 * Alias  : @assets/svgs/icon
 * Assets : 476
 * Date   : 2026-09-04T12:15:32.548Z
 *
 * ⚠️  Do not edit this file manually — re-run gen-assets.js instead.
 */
import { withThemeColor } from "../icon-wrapper";

import _OutlineAcademicCapSvg from "@assets/svgs/icon/outline/academic-cap.svg";
export const OutlineAcademicCapSvg = withThemeColor(_OutlineAcademicCapSvg);

import _OutlineAddAPhotoSvg from "@assets/svgs/icon/outline/add-a-photo.svg";
export const OutlineAddAPhotoSvg = withThemeColor(_OutlineAddAPhotoSvg);

import _OutlineAddUserSvg from "@assets/svgs/icon/outline/add-user.svg";
export const OutlineAddUserSvg = withThemeColor(_OutlineAddUserSvg);

import _OutlineAdjustmentsSvg from "@assets/svgs/icon/outline/adjustments.svg";
export const OutlineAdjustmentsSvg = withThemeColor(_OutlineAdjustmentsSvg);

import _OutlineAnnotationSvg from "@assets/svgs/icon/outline/annotation.svg";
export const OutlineAnnotationSvg = withThemeColor(_OutlineAnnotationSvg);

import _OutlineArchiveSvg from "@assets/svgs/icon/outline/archive.svg";
export const OutlineArchiveSvg = withThemeColor(_OutlineArchiveSvg);

import _OutlineArrowCircleDownSvg from "@assets/svgs/icon/outline/arrow-circle-down.svg";
export const OutlineArrowCircleDownSvg = withThemeColor(_OutlineArrowCircleDownSvg);

import _OutlineArrowCircleLeftSvg from "@assets/svgs/icon/outline/arrow-circle-left.svg";
export const OutlineArrowCircleLeftSvg = withThemeColor(_OutlineArrowCircleLeftSvg);

import _OutlineArrowCircleRightSvg from "@assets/svgs/icon/outline/arrow-circle-right.svg";
export const OutlineArrowCircleRightSvg = withThemeColor(_OutlineArrowCircleRightSvg);

import _OutlineArrowCircleUpSvg from "@assets/svgs/icon/outline/arrow-circle-up.svg";
export const OutlineArrowCircleUpSvg = withThemeColor(_OutlineArrowCircleUpSvg);

import _OutlineArrowDownSvg from "@assets/svgs/icon/outline/arrow-down.svg";
export const OutlineArrowDownSvg = withThemeColor(_OutlineArrowDownSvg);

import _OutlineArrowLeftSvg from "@assets/svgs/icon/outline/arrow-left.svg";
export const OutlineArrowLeftSvg = withThemeColor(_OutlineArrowLeftSvg);

import _OutlineArrowNarrowDownSvg from "@assets/svgs/icon/outline/arrow-narrow-down.svg";
export const OutlineArrowNarrowDownSvg = withThemeColor(_OutlineArrowNarrowDownSvg);

import _OutlineArrowNarrowLeftSvg from "@assets/svgs/icon/outline/arrow-narrow-left.svg";
export const OutlineArrowNarrowLeftSvg = withThemeColor(_OutlineArrowNarrowLeftSvg);

import _OutlineArrowNarrowRightSvg from "@assets/svgs/icon/outline/arrow-narrow-right.svg";
export const OutlineArrowNarrowRightSvg = withThemeColor(_OutlineArrowNarrowRightSvg);

import _OutlineArrowNarrowUpSvg from "@assets/svgs/icon/outline/arrow-narrow-up.svg";
export const OutlineArrowNarrowUpSvg = withThemeColor(_OutlineArrowNarrowUpSvg);

import _OutlineArrowRightSvg from "@assets/svgs/icon/outline/arrow-right.svg";
export const OutlineArrowRightSvg = withThemeColor(_OutlineArrowRightSvg);

import _OutlineArrowSmDownSvg from "@assets/svgs/icon/outline/arrow-sm-down.svg";
export const OutlineArrowSmDownSvg = withThemeColor(_OutlineArrowSmDownSvg);

import _OutlineArrowSmLeftSvg from "@assets/svgs/icon/outline/arrow-sm-left.svg";
export const OutlineArrowSmLeftSvg = withThemeColor(_OutlineArrowSmLeftSvg);

import _OutlineArrowSmRightSvg from "@assets/svgs/icon/outline/arrow-sm-right.svg";
export const OutlineArrowSmRightSvg = withThemeColor(_OutlineArrowSmRightSvg);

import _OutlineArrowSmUpSvg from "@assets/svgs/icon/outline/arrow-sm-up.svg";
export const OutlineArrowSmUpSvg = withThemeColor(_OutlineArrowSmUpSvg);

import _OutlineArrowUpSvg from "@assets/svgs/icon/outline/arrow-up.svg";
export const OutlineArrowUpSvg = withThemeColor(_OutlineArrowUpSvg);

import _OutlineArrowsExpandSvg from "@assets/svgs/icon/outline/arrows-expand.svg";
export const OutlineArrowsExpandSvg = withThemeColor(_OutlineArrowsExpandSvg);

import _OutlineAtSymbolSvg from "@assets/svgs/icon/outline/at-symbol.svg";
export const OutlineAtSymbolSvg = withThemeColor(_OutlineAtSymbolSvg);

import _OutlineBackspaceSvg from "@assets/svgs/icon/outline/backspace.svg";
export const OutlineBackspaceSvg = withThemeColor(_OutlineBackspaceSvg);

import _OutlineBadgeCheckSvg from "@assets/svgs/icon/outline/badge-check.svg";
export const OutlineBadgeCheckSvg = withThemeColor(_OutlineBadgeCheckSvg);

import _OutlineBanSvg from "@assets/svgs/icon/outline/ban.svg";
export const OutlineBanSvg = withThemeColor(_OutlineBanSvg);

import _OutlineBeakerSvg from "@assets/svgs/icon/outline/beaker.svg";
export const OutlineBeakerSvg = withThemeColor(_OutlineBeakerSvg);

import _OutlineBellSvg from "@assets/svgs/icon/outline/bell.svg";
export const OutlineBellSvg = withThemeColor(_OutlineBellSvg);

import _OutlineBookOpenSvg from "@assets/svgs/icon/outline/book-open.svg";
export const OutlineBookOpenSvg = withThemeColor(_OutlineBookOpenSvg);

import _OutlineBookmarkAltSvg from "@assets/svgs/icon/outline/bookmark-alt.svg";
export const OutlineBookmarkAltSvg = withThemeColor(_OutlineBookmarkAltSvg);

import _OutlineBookmarkSvg from "@assets/svgs/icon/outline/bookmark.svg";
export const OutlineBookmarkSvg = withThemeColor(_OutlineBookmarkSvg);

import _OutlineBriefcaseSvg from "@assets/svgs/icon/outline/briefcase.svg";
export const OutlineBriefcaseSvg = withThemeColor(_OutlineBriefcaseSvg);

import _OutlineCakeSvg from "@assets/svgs/icon/outline/cake.svg";
export const OutlineCakeSvg = withThemeColor(_OutlineCakeSvg);

import _OutlineCalculatorSvg from "@assets/svgs/icon/outline/calculator.svg";
export const OutlineCalculatorSvg = withThemeColor(_OutlineCalculatorSvg);

import _OutlineCalendarSvg from "@assets/svgs/icon/outline/calendar.svg";
export const OutlineCalendarSvg = withThemeColor(_OutlineCalendarSvg);

import _OutlineCameraSvg from "@assets/svgs/icon/outline/camera.svg";
export const OutlineCameraSvg = withThemeColor(_OutlineCameraSvg);

import _OutlineCashSvg from "@assets/svgs/icon/outline/cash.svg";
export const OutlineCashSvg = withThemeColor(_OutlineCashSvg);

import _OutlineChartBarSvg from "@assets/svgs/icon/outline/chart-bar.svg";
export const OutlineChartBarSvg = withThemeColor(_OutlineChartBarSvg);

import _OutlineChartPieSvg from "@assets/svgs/icon/outline/chart-pie.svg";
export const OutlineChartPieSvg = withThemeColor(_OutlineChartPieSvg);

import _OutlineChartSquareBarSvg from "@assets/svgs/icon/outline/chart-square-bar.svg";
export const OutlineChartSquareBarSvg = withThemeColor(_OutlineChartSquareBarSvg);

import _OutlineChatAlt2Svg from "@assets/svgs/icon/outline/chat-alt-2.svg";
export const OutlineChatAlt2Svg = withThemeColor(_OutlineChatAlt2Svg);

import _OutlineChatAltSvg from "@assets/svgs/icon/outline/chat-alt.svg";
export const OutlineChatAltSvg = withThemeColor(_OutlineChatAltSvg);

import _OutlineChatSvg from "@assets/svgs/icon/outline/chat.svg";
export const OutlineChatSvg = withThemeColor(_OutlineChatSvg);

import _OutlineCheckCircleSvg from "@assets/svgs/icon/outline/check-circle.svg";
export const OutlineCheckCircleSvg = withThemeColor(_OutlineCheckCircleSvg);

import _OutlineCheckSvg from "@assets/svgs/icon/outline/check.svg";
export const OutlineCheckSvg = withThemeColor(_OutlineCheckSvg);

import _OutlineCheveronDownSvg from "@assets/svgs/icon/outline/cheveron-down.svg";
export const OutlineCheveronDownSvg = withThemeColor(_OutlineCheveronDownSvg);

import _OutlineCheveronLeftSvg from "@assets/svgs/icon/outline/cheveron-left.svg";
export const OutlineCheveronLeftSvg = withThemeColor(_OutlineCheveronLeftSvg);

import _OutlineCheveronRightSvg from "@assets/svgs/icon/outline/cheveron-right.svg";
export const OutlineCheveronRightSvg = withThemeColor(_OutlineCheveronRightSvg);

import _OutlineCheveronUpSvg from "@assets/svgs/icon/outline/cheveron-up.svg";
export const OutlineCheveronUpSvg = withThemeColor(_OutlineCheveronUpSvg);

import _OutlineChevronDoubleDownSvg from "@assets/svgs/icon/outline/chevron-double-down.svg";
export const OutlineChevronDoubleDownSvg = withThemeColor(_OutlineChevronDoubleDownSvg);

import _OutlineChevronDoubleLeftSvg from "@assets/svgs/icon/outline/chevron-double-left.svg";
export const OutlineChevronDoubleLeftSvg = withThemeColor(_OutlineChevronDoubleLeftSvg);

import _OutlineChevronDoubleRightSvg from "@assets/svgs/icon/outline/chevron-double-right.svg";
export const OutlineChevronDoubleRightSvg = withThemeColor(_OutlineChevronDoubleRightSvg);

import _OutlineChevronDoubleUpSvg from "@assets/svgs/icon/outline/chevron-double-up.svg";
export const OutlineChevronDoubleUpSvg = withThemeColor(_OutlineChevronDoubleUpSvg);

import _OutlineChipSvg from "@assets/svgs/icon/outline/chip.svg";
export const OutlineChipSvg = withThemeColor(_OutlineChipSvg);

import _OutlineClipboardCheckSvg from "@assets/svgs/icon/outline/clipboard-check.svg";
export const OutlineClipboardCheckSvg = withThemeColor(_OutlineClipboardCheckSvg);

import _OutlineClipboardCopySvg from "@assets/svgs/icon/outline/clipboard-copy.svg";
export const OutlineClipboardCopySvg = withThemeColor(_OutlineClipboardCopySvg);

import _OutlineClipboardListSvg from "@assets/svgs/icon/outline/clipboard-list.svg";
export const OutlineClipboardListSvg = withThemeColor(_OutlineClipboardListSvg);

import _OutlineClipboardSvg from "@assets/svgs/icon/outline/clipboard.svg";
export const OutlineClipboardSvg = withThemeColor(_OutlineClipboardSvg);

import _OutlineClockSvg from "@assets/svgs/icon/outline/clock.svg";
export const OutlineClockSvg = withThemeColor(_OutlineClockSvg);

import _OutlineCloudDownloadSvg from "@assets/svgs/icon/outline/cloud-download.svg";
export const OutlineCloudDownloadSvg = withThemeColor(_OutlineCloudDownloadSvg);

import _OutlineCloudUploadSvg from "@assets/svgs/icon/outline/cloud-upload.svg";
export const OutlineCloudUploadSvg = withThemeColor(_OutlineCloudUploadSvg);

import _OutlineCloudSvg from "@assets/svgs/icon/outline/cloud.svg";
export const OutlineCloudSvg = withThemeColor(_OutlineCloudSvg);

import _OutlineCodeSvg from "@assets/svgs/icon/outline/code.svg";
export const OutlineCodeSvg = withThemeColor(_OutlineCodeSvg);

import _OutlineCogSvg from "@assets/svgs/icon/outline/cog.svg";
export const OutlineCogSvg = withThemeColor(_OutlineCogSvg);

import _OutlineCollectionSvg from "@assets/svgs/icon/outline/collection.svg";
export const OutlineCollectionSvg = withThemeColor(_OutlineCollectionSvg);

import _OutlineColorSwatchSvg from "@assets/svgs/icon/outline/color-swatch.svg";
export const OutlineColorSwatchSvg = withThemeColor(_OutlineColorSwatchSvg);

import _OutlineCreditCardSvg from "@assets/svgs/icon/outline/credit-card.svg";
export const OutlineCreditCardSvg = withThemeColor(_OutlineCreditCardSvg);

import _OutlineCubeTransparentSvg from "@assets/svgs/icon/outline/cube-transparent.svg";
export const OutlineCubeTransparentSvg = withThemeColor(_OutlineCubeTransparentSvg);

import _OutlineCubeSvg from "@assets/svgs/icon/outline/cube.svg";
export const OutlineCubeSvg = withThemeColor(_OutlineCubeSvg);

import _OutlineCurrencyBangladeshiSvg from "@assets/svgs/icon/outline/currency-bangladeshi.svg";
export const OutlineCurrencyBangladeshiSvg = withThemeColor(_OutlineCurrencyBangladeshiSvg);

import _OutlineCurrencyDollarSvg from "@assets/svgs/icon/outline/currency-dollar.svg";
export const OutlineCurrencyDollarSvg = withThemeColor(_OutlineCurrencyDollarSvg);

import _OutlineCurrencyEuroSvg from "@assets/svgs/icon/outline/currency-euro.svg";
export const OutlineCurrencyEuroSvg = withThemeColor(_OutlineCurrencyEuroSvg);

import _OutlineCurrencyPoundSvg from "@assets/svgs/icon/outline/currency-pound.svg";
export const OutlineCurrencyPoundSvg = withThemeColor(_OutlineCurrencyPoundSvg);

import _OutlineCurrencyRupeeSvg from "@assets/svgs/icon/outline/currency-rupee.svg";
export const OutlineCurrencyRupeeSvg = withThemeColor(_OutlineCurrencyRupeeSvg);

import _OutlineCurrencyYenSvg from "@assets/svgs/icon/outline/currency-yen.svg";
export const OutlineCurrencyYenSvg = withThemeColor(_OutlineCurrencyYenSvg);

import _OutlineCursorClickSvg from "@assets/svgs/icon/outline/cursor-click.svg";
export const OutlineCursorClickSvg = withThemeColor(_OutlineCursorClickSvg);

import _OutlineDatabaseSvg from "@assets/svgs/icon/outline/database.svg";
export const OutlineDatabaseSvg = withThemeColor(_OutlineDatabaseSvg);

import _OutlineDesktopComputerSvg from "@assets/svgs/icon/outline/desktop-computer.svg";
export const OutlineDesktopComputerSvg = withThemeColor(_OutlineDesktopComputerSvg);

import _OutlineDeviceMobileSvg from "@assets/svgs/icon/outline/device-mobile.svg";
export const OutlineDeviceMobileSvg = withThemeColor(_OutlineDeviceMobileSvg);

import _OutlineDeviceTabletSvg from "@assets/svgs/icon/outline/device-tablet.svg";
export const OutlineDeviceTabletSvg = withThemeColor(_OutlineDeviceTabletSvg);

import _OutlineDocumentAddSvg from "@assets/svgs/icon/outline/document-add.svg";
export const OutlineDocumentAddSvg = withThemeColor(_OutlineDocumentAddSvg);

import _OutlineDocumentDownloadSvg from "@assets/svgs/icon/outline/document-download.svg";
export const OutlineDocumentDownloadSvg = withThemeColor(_OutlineDocumentDownloadSvg);

import _OutlineDocumentDuplicateSvg from "@assets/svgs/icon/outline/document-duplicate.svg";
export const OutlineDocumentDuplicateSvg = withThemeColor(_OutlineDocumentDuplicateSvg);

import _OutlineDocumentRemoveSvg from "@assets/svgs/icon/outline/document-remove.svg";
export const OutlineDocumentRemoveSvg = withThemeColor(_OutlineDocumentRemoveSvg);

import _OutlineDocumentReportSvg from "@assets/svgs/icon/outline/document-report.svg";
export const OutlineDocumentReportSvg = withThemeColor(_OutlineDocumentReportSvg);

import _OutlineDocumentSearchSvg from "@assets/svgs/icon/outline/document-search.svg";
export const OutlineDocumentSearchSvg = withThemeColor(_OutlineDocumentSearchSvg);

import _OutlineDocumentTextSvg from "@assets/svgs/icon/outline/document-text.svg";
export const OutlineDocumentTextSvg = withThemeColor(_OutlineDocumentTextSvg);

import _OutlineDocumentSvg from "@assets/svgs/icon/outline/document.svg";
export const OutlineDocumentSvg = withThemeColor(_OutlineDocumentSvg);

import _OutlineDotsCircleHorizontalSvg from "@assets/svgs/icon/outline/dots-circle-horizontal.svg";
export const OutlineDotsCircleHorizontalSvg = withThemeColor(_OutlineDotsCircleHorizontalSvg);

import _OutlineDotsHorizontalSvg from "@assets/svgs/icon/outline/dots-horizontal.svg";
export const OutlineDotsHorizontalSvg = withThemeColor(_OutlineDotsHorizontalSvg);

import _OutlineDotsVerticalSvg from "@assets/svgs/icon/outline/dots-vertical.svg";
export const OutlineDotsVerticalSvg = withThemeColor(_OutlineDotsVerticalSvg);

import _OutlineDoubleCheckSvg from "@assets/svgs/icon/outline/double-check.svg";
export const OutlineDoubleCheckSvg = withThemeColor(_OutlineDoubleCheckSvg);

import _OutlineDownloadSvg from "@assets/svgs/icon/outline/download.svg";
export const OutlineDownloadSvg = withThemeColor(_OutlineDownloadSvg);

import _OutlineDuplicateSvg from "@assets/svgs/icon/outline/duplicate.svg";
export const OutlineDuplicateSvg = withThemeColor(_OutlineDuplicateSvg);

import _OutlineEmojiHappySvg from "@assets/svgs/icon/outline/emoji-happy.svg";
export const OutlineEmojiHappySvg = withThemeColor(_OutlineEmojiHappySvg);

import _OutlineEmojiSadSvg from "@assets/svgs/icon/outline/emoji-sad.svg";
export const OutlineEmojiSadSvg = withThemeColor(_OutlineEmojiSadSvg);

import _OutlineExclamationCircleSvg from "@assets/svgs/icon/outline/exclamation-circle.svg";
export const OutlineExclamationCircleSvg = withThemeColor(_OutlineExclamationCircleSvg);

import _OutlineExclamationSvg from "@assets/svgs/icon/outline/exclamation.svg";
export const OutlineExclamationSvg = withThemeColor(_OutlineExclamationSvg);

import _OutlineExpandSvg from "@assets/svgs/icon/outline/expand.svg";
export const OutlineExpandSvg = withThemeColor(_OutlineExpandSvg);

import _OutlineExternalLinkSvg from "@assets/svgs/icon/outline/external-link.svg";
export const OutlineExternalLinkSvg = withThemeColor(_OutlineExternalLinkSvg);

import _OutlineEyeOffSvg from "@assets/svgs/icon/outline/eye-off.svg";
export const OutlineEyeOffSvg = withThemeColor(_OutlineEyeOffSvg);

import _OutlineEyeSvg from "@assets/svgs/icon/outline/eye.svg";
export const OutlineEyeSvg = withThemeColor(_OutlineEyeSvg);

import _OutlineFastForwardSvg from "@assets/svgs/icon/outline/fast-forward.svg";
export const OutlineFastForwardSvg = withThemeColor(_OutlineFastForwardSvg);

import _OutlineFilmSvg from "@assets/svgs/icon/outline/film.svg";
export const OutlineFilmSvg = withThemeColor(_OutlineFilmSvg);

import _OutlineFilterSvg from "@assets/svgs/icon/outline/filter.svg";
export const OutlineFilterSvg = withThemeColor(_OutlineFilterSvg);

import _OutlineFingerPrintSvg from "@assets/svgs/icon/outline/finger-print.svg";
export const OutlineFingerPrintSvg = withThemeColor(_OutlineFingerPrintSvg);

import _OutlineFireSvg from "@assets/svgs/icon/outline/fire.svg";
export const OutlineFireSvg = withThemeColor(_OutlineFireSvg);

import _OutlineFlagSvg from "@assets/svgs/icon/outline/flag.svg";
export const OutlineFlagSvg = withThemeColor(_OutlineFlagSvg);

import _OutlineFolderAddSvg from "@assets/svgs/icon/outline/folder-add.svg";
export const OutlineFolderAddSvg = withThemeColor(_OutlineFolderAddSvg);

import _OutlineFolderDownloadSvg from "@assets/svgs/icon/outline/folder-download.svg";
export const OutlineFolderDownloadSvg = withThemeColor(_OutlineFolderDownloadSvg);

import _OutlineFolderOpenSvg from "@assets/svgs/icon/outline/folder-open.svg";
export const OutlineFolderOpenSvg = withThemeColor(_OutlineFolderOpenSvg);

import _OutlineFolderRemoveSvg from "@assets/svgs/icon/outline/folder-remove.svg";
export const OutlineFolderRemoveSvg = withThemeColor(_OutlineFolderRemoveSvg);

import _OutlineFolderSvg from "@assets/svgs/icon/outline/folder.svg";
export const OutlineFolderSvg = withThemeColor(_OutlineFolderSvg);

import _OutlineGiftSvg from "@assets/svgs/icon/outline/gift.svg";
export const OutlineGiftSvg = withThemeColor(_OutlineGiftSvg);

import _OutlineGlobeAltSvg from "@assets/svgs/icon/outline/globe-alt.svg";
export const OutlineGlobeAltSvg = withThemeColor(_OutlineGlobeAltSvg);

import _OutlineGlobeSvg from "@assets/svgs/icon/outline/globe.svg";
export const OutlineGlobeSvg = withThemeColor(_OutlineGlobeSvg);

import _OutlineHandSvg from "@assets/svgs/icon/outline/hand.svg";
export const OutlineHandSvg = withThemeColor(_OutlineHandSvg);

import _OutlineHashtagSvg from "@assets/svgs/icon/outline/hashtag.svg";
export const OutlineHashtagSvg = withThemeColor(_OutlineHashtagSvg);

import _OutlineHeartSvg from "@assets/svgs/icon/outline/heart.svg";
export const OutlineHeartSvg = withThemeColor(_OutlineHeartSvg);

import _OutlineHomeSvg from "@assets/svgs/icon/outline/home.svg";
export const OutlineHomeSvg = withThemeColor(_OutlineHomeSvg);

import _OutlineIconUserRemoveSvg from "@assets/svgs/icon/outline/icon-user-remove.svg";
export const OutlineIconUserRemoveSvg = withThemeColor(_OutlineIconUserRemoveSvg);

import _OutlineIdentificationSvg from "@assets/svgs/icon/outline/identification.svg";
export const OutlineIdentificationSvg = withThemeColor(_OutlineIdentificationSvg);

import _OutlineInboxInSvg from "@assets/svgs/icon/outline/inbox-in.svg";
export const OutlineInboxInSvg = withThemeColor(_OutlineInboxInSvg);

import _OutlineInboxSvg from "@assets/svgs/icon/outline/inbox.svg";
export const OutlineInboxSvg = withThemeColor(_OutlineInboxSvg);

import _OutlineInformationCircleSvg from "@assets/svgs/icon/outline/information-circle.svg";
export const OutlineInformationCircleSvg = withThemeColor(_OutlineInformationCircleSvg);

import _OutlineKeySvg from "@assets/svgs/icon/outline/key.svg";
export const OutlineKeySvg = withThemeColor(_OutlineKeySvg);

import _OutlineLibrarySvg from "@assets/svgs/icon/outline/library.svg";
export const OutlineLibrarySvg = withThemeColor(_OutlineLibrarySvg);

import _OutlineLightBulbSvg from "@assets/svgs/icon/outline/light-bulb.svg";
export const OutlineLightBulbSvg = withThemeColor(_OutlineLightBulbSvg);

import _OutlineLightningBoltSvg from "@assets/svgs/icon/outline/lightning-bolt.svg";
export const OutlineLightningBoltSvg = withThemeColor(_OutlineLightningBoltSvg);

import _OutlineLinkSvg from "@assets/svgs/icon/outline/link.svg";
export const OutlineLinkSvg = withThemeColor(_OutlineLinkSvg);

import _OutlineLocationMarkerSvg from "@assets/svgs/icon/outline/location-marker.svg";
export const OutlineLocationMarkerSvg = withThemeColor(_OutlineLocationMarkerSvg);

import _OutlineLockClosedSvg from "@assets/svgs/icon/outline/lock-closed.svg";
export const OutlineLockClosedSvg = withThemeColor(_OutlineLockClosedSvg);

import _OutlineLockOpenSvg from "@assets/svgs/icon/outline/lock-open.svg";
export const OutlineLockOpenSvg = withThemeColor(_OutlineLockOpenSvg);

import _OutlineLogout1Svg from "@assets/svgs/icon/outline/logout-1.svg";
export const OutlineLogout1Svg = withThemeColor(_OutlineLogout1Svg);

import _OutlineLogoutSvg from "@assets/svgs/icon/outline/logout.svg";
export const OutlineLogoutSvg = withThemeColor(_OutlineLogoutSvg);

import _OutlineMailOpenSvg from "@assets/svgs/icon/outline/mail-open.svg";
export const OutlineMailOpenSvg = withThemeColor(_OutlineMailOpenSvg);

import _OutlineMailSvg from "@assets/svgs/icon/outline/mail.svg";
export const OutlineMailSvg = withThemeColor(_OutlineMailSvg);

import _OutlineMapSvg from "@assets/svgs/icon/outline/map.svg";
export const OutlineMapSvg = withThemeColor(_OutlineMapSvg);

import _OutlineMenuAlt1Svg from "@assets/svgs/icon/outline/menu-alt-1.svg";
export const OutlineMenuAlt1Svg = withThemeColor(_OutlineMenuAlt1Svg);

import _OutlineMenuAlt2Svg from "@assets/svgs/icon/outline/menu-alt-2.svg";
export const OutlineMenuAlt2Svg = withThemeColor(_OutlineMenuAlt2Svg);

import _OutlineMenuAlt3Svg from "@assets/svgs/icon/outline/menu-alt-3.svg";
export const OutlineMenuAlt3Svg = withThemeColor(_OutlineMenuAlt3Svg);

import _OutlineMenuAlt4Svg from "@assets/svgs/icon/outline/menu-alt-4.svg";
export const OutlineMenuAlt4Svg = withThemeColor(_OutlineMenuAlt4Svg);

import _OutlineMenuSvg from "@assets/svgs/icon/outline/menu.svg";
export const OutlineMenuSvg = withThemeColor(_OutlineMenuSvg);

import _OutlineMicrophoneSvg from "@assets/svgs/icon/outline/microphone.svg";
export const OutlineMicrophoneSvg = withThemeColor(_OutlineMicrophoneSvg);

import _OutlineMinusCircleSvg from "@assets/svgs/icon/outline/minus-circle.svg";
export const OutlineMinusCircleSvg = withThemeColor(_OutlineMinusCircleSvg);

import _OutlineMinusSmSvg from "@assets/svgs/icon/outline/minus-sm.svg";
export const OutlineMinusSmSvg = withThemeColor(_OutlineMinusSmSvg);

import _OutlineMinusSvg from "@assets/svgs/icon/outline/minus.svg";
export const OutlineMinusSvg = withThemeColor(_OutlineMinusSvg);

import _OutlineMoonSvg from "@assets/svgs/icon/outline/moon.svg";
export const OutlineMoonSvg = withThemeColor(_OutlineMoonSvg);

import _OutlineMusicNoteSvg from "@assets/svgs/icon/outline/music-note.svg";
export const OutlineMusicNoteSvg = withThemeColor(_OutlineMusicNoteSvg);

import _OutlineNewspaperSvg from "@assets/svgs/icon/outline/newspaper.svg";
export const OutlineNewspaperSvg = withThemeColor(_OutlineNewspaperSvg);

import _OutlineOfficeBuildingSvg from "@assets/svgs/icon/outline/office-building.svg";
export const OutlineOfficeBuildingSvg = withThemeColor(_OutlineOfficeBuildingSvg);

import _OutlinePaperAirplaneSvg from "@assets/svgs/icon/outline/paper-airplane.svg";
export const OutlinePaperAirplaneSvg = withThemeColor(_OutlinePaperAirplaneSvg);

import _OutlinePaperClipSvg from "@assets/svgs/icon/outline/paper-clip.svg";
export const OutlinePaperClipSvg = withThemeColor(_OutlinePaperClipSvg);

import _OutlinePauseSvg from "@assets/svgs/icon/outline/pause.svg";
export const OutlinePauseSvg = withThemeColor(_OutlinePauseSvg);

import _OutlinePencilAltSvg from "@assets/svgs/icon/outline/pencil-alt.svg";
export const OutlinePencilAltSvg = withThemeColor(_OutlinePencilAltSvg);

import _OutlinePencilSvg from "@assets/svgs/icon/outline/pencil.svg";
export const OutlinePencilSvg = withThemeColor(_OutlinePencilSvg);

import _OutlinePhoneIncomingSvg from "@assets/svgs/icon/outline/phone-incoming.svg";
export const OutlinePhoneIncomingSvg = withThemeColor(_OutlinePhoneIncomingSvg);

import _OutlinePhoneMissedCallSvg from "@assets/svgs/icon/outline/phone-missed-call.svg";
export const OutlinePhoneMissedCallSvg = withThemeColor(_OutlinePhoneMissedCallSvg);

import _OutlinePhoneOutgoingSvg from "@assets/svgs/icon/outline/phone-outgoing.svg";
export const OutlinePhoneOutgoingSvg = withThemeColor(_OutlinePhoneOutgoingSvg);

import _OutlinePhoneSvg from "@assets/svgs/icon/outline/phone.svg";
export const OutlinePhoneSvg = withThemeColor(_OutlinePhoneSvg);

import _OutlinePhotographSvg from "@assets/svgs/icon/outline/photograph.svg";
export const OutlinePhotographSvg = withThemeColor(_OutlinePhotographSvg);

import _OutlinePinOffSvg from "@assets/svgs/icon/outline/pin-off.svg";
export const OutlinePinOffSvg = withThemeColor(_OutlinePinOffSvg);

import _OutlinePlaySvg from "@assets/svgs/icon/outline/play.svg";
export const OutlinePlaySvg = withThemeColor(_OutlinePlaySvg);

import _OutlinePlusCircleSvg from "@assets/svgs/icon/outline/plus-circle.svg";
export const OutlinePlusCircleSvg = withThemeColor(_OutlinePlusCircleSvg);

import _OutlinePlusSmSvg from "@assets/svgs/icon/outline/plus-sm.svg";
export const OutlinePlusSmSvg = withThemeColor(_OutlinePlusSmSvg);

import _OutlinePlusSvg from "@assets/svgs/icon/outline/plus.svg";
export const OutlinePlusSvg = withThemeColor(_OutlinePlusSvg);

import _OutlinePresentationChartBarSvg from "@assets/svgs/icon/outline/presentation-chart-bar.svg";
export const OutlinePresentationChartBarSvg = withThemeColor(_OutlinePresentationChartBarSvg);

import _OutlinePresentationChartLineSvg from "@assets/svgs/icon/outline/presentation-chart-line.svg";
export const OutlinePresentationChartLineSvg = withThemeColor(_OutlinePresentationChartLineSvg);

import _OutlinePrinterSvg from "@assets/svgs/icon/outline/printer.svg";
export const OutlinePrinterSvg = withThemeColor(_OutlinePrinterSvg);

import _OutlinePushPinSvg from "@assets/svgs/icon/outline/push-pin.svg";
export const OutlinePushPinSvg = withThemeColor(_OutlinePushPinSvg);

import _OutlinePuzzleSvg from "@assets/svgs/icon/outline/puzzle.svg";
export const OutlinePuzzleSvg = withThemeColor(_OutlinePuzzleSvg);

import _OutlineQrcodeSvg from "@assets/svgs/icon/outline/qrcode.svg";
export const OutlineQrcodeSvg = withThemeColor(_OutlineQrcodeSvg);

import _OutlineQuestionMarkCircleSvg from "@assets/svgs/icon/outline/question-mark-circle.svg";
export const OutlineQuestionMarkCircleSvg = withThemeColor(_OutlineQuestionMarkCircleSvg);

import _OutlineReceiptRefundSvg from "@assets/svgs/icon/outline/receipt-refund.svg";
export const OutlineReceiptRefundSvg = withThemeColor(_OutlineReceiptRefundSvg);

import _OutlineReceiptTaxSvg from "@assets/svgs/icon/outline/receipt-tax.svg";
export const OutlineReceiptTaxSvg = withThemeColor(_OutlineReceiptTaxSvg);

import _OutlineRefreshSvg from "@assets/svgs/icon/outline/refresh.svg";
export const OutlineRefreshSvg = withThemeColor(_OutlineRefreshSvg);

import _OutlineReplySvg from "@assets/svgs/icon/outline/reply.svg";
export const OutlineReplySvg = withThemeColor(_OutlineReplySvg);

import _OutlineRewindSvg from "@assets/svgs/icon/outline/rewind.svg";
export const OutlineRewindSvg = withThemeColor(_OutlineRewindSvg);

import _OutlineRssSvg from "@assets/svgs/icon/outline/rss.svg";
export const OutlineRssSvg = withThemeColor(_OutlineRssSvg);

import _OutlineSaveAsSvg from "@assets/svgs/icon/outline/save-as.svg";
export const OutlineSaveAsSvg = withThemeColor(_OutlineSaveAsSvg);

import _OutlineSaveSvg from "@assets/svgs/icon/outline/save.svg";
export const OutlineSaveSvg = withThemeColor(_OutlineSaveSvg);

import _OutlineScaleSvg from "@assets/svgs/icon/outline/scale.svg";
export const OutlineScaleSvg = withThemeColor(_OutlineScaleSvg);

import _OutlineScissorsSvg from "@assets/svgs/icon/outline/scissors.svg";
export const OutlineScissorsSvg = withThemeColor(_OutlineScissorsSvg);

import _OutlineSearchCircleSvg from "@assets/svgs/icon/outline/search-circle.svg";
export const OutlineSearchCircleSvg = withThemeColor(_OutlineSearchCircleSvg);

import _OutlineSearchSvg from "@assets/svgs/icon/outline/search.svg";
export const OutlineSearchSvg = withThemeColor(_OutlineSearchSvg);

import _OutlineSelectorSvg from "@assets/svgs/icon/outline/selector.svg";
export const OutlineSelectorSvg = withThemeColor(_OutlineSelectorSvg);

import _OutlineServerSvg from "@assets/svgs/icon/outline/server.svg";
export const OutlineServerSvg = withThemeColor(_OutlineServerSvg);

import _OutlineShareSvg from "@assets/svgs/icon/outline/share.svg";
export const OutlineShareSvg = withThemeColor(_OutlineShareSvg);

import _OutlineShieldCheckSvg from "@assets/svgs/icon/outline/shield-check.svg";
export const OutlineShieldCheckSvg = withThemeColor(_OutlineShieldCheckSvg);

import _OutlineShieldExclamationSvg from "@assets/svgs/icon/outline/shield-exclamation.svg";
export const OutlineShieldExclamationSvg = withThemeColor(_OutlineShieldExclamationSvg);

import _OutlineShoppingBagSvg from "@assets/svgs/icon/outline/shopping-bag.svg";
export const OutlineShoppingBagSvg = withThemeColor(_OutlineShoppingBagSvg);

import _OutlineShoppingCartSvg from "@assets/svgs/icon/outline/shopping-cart.svg";
export const OutlineShoppingCartSvg = withThemeColor(_OutlineShoppingCartSvg);

import _OutlineSmViewGridAddSvg from "@assets/svgs/icon/outline/sm-view-grid-add.svg";
export const OutlineSmViewGridAddSvg = withThemeColor(_OutlineSmViewGridAddSvg);

import _OutlineSortAscendingSvg from "@assets/svgs/icon/outline/sort-ascending.svg";
export const OutlineSortAscendingSvg = withThemeColor(_OutlineSortAscendingSvg);

import _OutlineSortDescendingSvg from "@assets/svgs/icon/outline/sort-descending.svg";
export const OutlineSortDescendingSvg = withThemeColor(_OutlineSortDescendingSvg);

import _OutlineSparklesSvg from "@assets/svgs/icon/outline/sparkles.svg";
export const OutlineSparklesSvg = withThemeColor(_OutlineSparklesSvg);

import _OutlineSpeakerphoneSvg from "@assets/svgs/icon/outline/speakerphone.svg";
export const OutlineSpeakerphoneSvg = withThemeColor(_OutlineSpeakerphoneSvg);

import _OutlineStarSvg from "@assets/svgs/icon/outline/star.svg";
export const OutlineStarSvg = withThemeColor(_OutlineStarSvg);

import _OutlineStatusOfflineSvg from "@assets/svgs/icon/outline/status-offline.svg";
export const OutlineStatusOfflineSvg = withThemeColor(_OutlineStatusOfflineSvg);

import _OutlineStatusOnlineSvg from "@assets/svgs/icon/outline/status-online.svg";
export const OutlineStatusOnlineSvg = withThemeColor(_OutlineStatusOnlineSvg);

import _OutlineStopSvg from "@assets/svgs/icon/outline/stop.svg";
export const OutlineStopSvg = withThemeColor(_OutlineStopSvg);

import _OutlineSunSvg from "@assets/svgs/icon/outline/sun.svg";
export const OutlineSunSvg = withThemeColor(_OutlineSunSvg);

import _OutlineSupportSvg from "@assets/svgs/icon/outline/support.svg";
export const OutlineSupportSvg = withThemeColor(_OutlineSupportSvg);

import _OutlineSwitchHorizontalSvg from "@assets/svgs/icon/outline/switch-horizontal.svg";
export const OutlineSwitchHorizontalSvg = withThemeColor(_OutlineSwitchHorizontalSvg);

import _OutlineSwitchVerticalSvg from "@assets/svgs/icon/outline/switch-vertical.svg";
export const OutlineSwitchVerticalSvg = withThemeColor(_OutlineSwitchVerticalSvg);

import _OutlineTableSvg from "@assets/svgs/icon/outline/table.svg";
export const OutlineTableSvg = withThemeColor(_OutlineTableSvg);

import _OutlineTagSvg from "@assets/svgs/icon/outline/tag.svg";
export const OutlineTagSvg = withThemeColor(_OutlineTagSvg);

import _OutlineTemplateSvg from "@assets/svgs/icon/outline/template.svg";
export const OutlineTemplateSvg = withThemeColor(_OutlineTemplateSvg);

import _OutlineTerminalSvg from "@assets/svgs/icon/outline/terminal.svg";
export const OutlineTerminalSvg = withThemeColor(_OutlineTerminalSvg);

import _OutlineThumbDownSvg from "@assets/svgs/icon/outline/thumb-down.svg";
export const OutlineThumbDownSvg = withThemeColor(_OutlineThumbDownSvg);

import _OutlineThumbUpSvg from "@assets/svgs/icon/outline/thumb-up.svg";
export const OutlineThumbUpSvg = withThemeColor(_OutlineThumbUpSvg);

import _OutlineTicketSvg from "@assets/svgs/icon/outline/ticket.svg";
export const OutlineTicketSvg = withThemeColor(_OutlineTicketSvg);

import _OutlineTranslateSvg from "@assets/svgs/icon/outline/translate.svg";
export const OutlineTranslateSvg = withThemeColor(_OutlineTranslateSvg);

import _OutlineTrashSvg from "@assets/svgs/icon/outline/trash.svg";
export const OutlineTrashSvg = withThemeColor(_OutlineTrashSvg);

import _OutlineTrendingDownSvg from "@assets/svgs/icon/outline/trending-down.svg";
export const OutlineTrendingDownSvg = withThemeColor(_OutlineTrendingDownSvg);

import _OutlineTrendingUpSvg from "@assets/svgs/icon/outline/trending-up.svg";
export const OutlineTrendingUpSvg = withThemeColor(_OutlineTrendingUpSvg);

import _OutlineTruckSvg from "@assets/svgs/icon/outline/truck.svg";
export const OutlineTruckSvg = withThemeColor(_OutlineTruckSvg);

import _OutlineUploadSvg from "@assets/svgs/icon/outline/upload.svg";
export const OutlineUploadSvg = withThemeColor(_OutlineUploadSvg);

import _OutlineUserAddSvg from "@assets/svgs/icon/outline/user-add.svg";
export const OutlineUserAddSvg = withThemeColor(_OutlineUserAddSvg);

import _OutlineUserCircleSvg from "@assets/svgs/icon/outline/user-circle.svg";
export const OutlineUserCircleSvg = withThemeColor(_OutlineUserCircleSvg);

import _OutlineUserGroupSvg from "@assets/svgs/icon/outline/user-group.svg";
export const OutlineUserGroupSvg = withThemeColor(_OutlineUserGroupSvg);

import _OutlineUserSvg from "@assets/svgs/icon/outline/user.svg";
export const OutlineUserSvg = withThemeColor(_OutlineUserSvg);

import _OutlineUsersSvg from "@assets/svgs/icon/outline/users.svg";
export const OutlineUsersSvg = withThemeColor(_OutlineUsersSvg);

import _OutlineVariableSvg from "@assets/svgs/icon/outline/variable.svg";
export const OutlineVariableSvg = withThemeColor(_OutlineVariableSvg);

import _OutlineVideoCameraSvg from "@assets/svgs/icon/outline/video-camera.svg";
export const OutlineVideoCameraSvg = withThemeColor(_OutlineVideoCameraSvg);

import _OutlineViewBoardsSvg from "@assets/svgs/icon/outline/view-boards.svg";
export const OutlineViewBoardsSvg = withThemeColor(_OutlineViewBoardsSvg);

import _OutlineViewGridSvg from "@assets/svgs/icon/outline/view-grid.svg";
export const OutlineViewGridSvg = withThemeColor(_OutlineViewGridSvg);

import _OutlineViewListSvg from "@assets/svgs/icon/outline/view-list.svg";
export const OutlineViewListSvg = withThemeColor(_OutlineViewListSvg);

import _OutlineVolumeOff1Svg from "@assets/svgs/icon/outline/volume-off-1.svg";
export const OutlineVolumeOff1Svg = withThemeColor(_OutlineVolumeOff1Svg);

import _OutlineVolumeOffSvg from "@assets/svgs/icon/outline/volume-off.svg";
export const OutlineVolumeOffSvg = withThemeColor(_OutlineVolumeOffSvg);

import _OutlineVolumeUp1Svg from "@assets/svgs/icon/outline/volume-up-1.svg";
export const OutlineVolumeUp1Svg = withThemeColor(_OutlineVolumeUp1Svg);

import _OutlineVolumeUpSvg from "@assets/svgs/icon/outline/volume-up.svg";
export const OutlineVolumeUpSvg = withThemeColor(_OutlineVolumeUpSvg);

import _OutlineWifiSvg from "@assets/svgs/icon/outline/wifi.svg";
export const OutlineWifiSvg = withThemeColor(_OutlineWifiSvg);

import _OutlineXCircleSvg from "@assets/svgs/icon/outline/x-circle.svg";
export const OutlineXCircleSvg = withThemeColor(_OutlineXCircleSvg);

import _OutlineXSvg from "@assets/svgs/icon/outline/x.svg";
export const OutlineXSvg = withThemeColor(_OutlineXSvg);

import _OutlineZoomInSvg from "@assets/svgs/icon/outline/zoom-in.svg";
export const OutlineZoomInSvg = withThemeColor(_OutlineZoomInSvg);

import _OutlineZoomOutSvg from "@assets/svgs/icon/outline/zoom-out.svg";
export const OutlineZoomOutSvg = withThemeColor(_OutlineZoomOutSvg);

import _SolidAcademicCapSvg from "@assets/svgs/icon/solid/academic-cap.svg";
export const SolidAcademicCapSvg = withThemeColor(_SolidAcademicCapSvg);

import _SolidAddAPhotoSvg from "@assets/svgs/icon/solid/add-a-photo.svg";
export const SolidAddAPhotoSvg = withThemeColor(_SolidAddAPhotoSvg);

import _SolidAdjustmentsSvg from "@assets/svgs/icon/solid/adjustments.svg";
export const SolidAdjustmentsSvg = withThemeColor(_SolidAdjustmentsSvg);

import _SolidAnnotationSvg from "@assets/svgs/icon/solid/annotation.svg";
export const SolidAnnotationSvg = withThemeColor(_SolidAnnotationSvg);

import _SolidArchiveSvg from "@assets/svgs/icon/solid/archive.svg";
export const SolidArchiveSvg = withThemeColor(_SolidArchiveSvg);

import _SolidArrowCircleDownSvg from "@assets/svgs/icon/solid/arrow-circle-down.svg";
export const SolidArrowCircleDownSvg = withThemeColor(_SolidArrowCircleDownSvg);

import _SolidArrowCircleLeftSvg from "@assets/svgs/icon/solid/arrow-circle-left.svg";
export const SolidArrowCircleLeftSvg = withThemeColor(_SolidArrowCircleLeftSvg);

import _SolidArrowCircleRightSvg from "@assets/svgs/icon/solid/arrow-circle-right.svg";
export const SolidArrowCircleRightSvg = withThemeColor(_SolidArrowCircleRightSvg);

import _SolidArrowCircleUpSvg from "@assets/svgs/icon/solid/arrow-circle-up.svg";
export const SolidArrowCircleUpSvg = withThemeColor(_SolidArrowCircleUpSvg);

import _SolidArrowDownSvg from "@assets/svgs/icon/solid/arrow-down.svg";
export const SolidArrowDownSvg = withThemeColor(_SolidArrowDownSvg);

import _SolidArrowLeftSvg from "@assets/svgs/icon/solid/arrow-left.svg";
export const SolidArrowLeftSvg = withThemeColor(_SolidArrowLeftSvg);

import _SolidArrowNarrowDownSvg from "@assets/svgs/icon/solid/arrow-narrow-down.svg";
export const SolidArrowNarrowDownSvg = withThemeColor(_SolidArrowNarrowDownSvg);

import _SolidArrowNarrowLeftSvg from "@assets/svgs/icon/solid/arrow-narrow-left.svg";
export const SolidArrowNarrowLeftSvg = withThemeColor(_SolidArrowNarrowLeftSvg);

import _SolidArrowNarrowRightSvg from "@assets/svgs/icon/solid/arrow-narrow-right.svg";
export const SolidArrowNarrowRightSvg = withThemeColor(_SolidArrowNarrowRightSvg);

import _SolidArrowNarrowUpSvg from "@assets/svgs/icon/solid/arrow-narrow-up.svg";
export const SolidArrowNarrowUpSvg = withThemeColor(_SolidArrowNarrowUpSvg);

import _SolidArrowRightSvg from "@assets/svgs/icon/solid/arrow-right.svg";
export const SolidArrowRightSvg = withThemeColor(_SolidArrowRightSvg);

import _SolidArrowSmDownSvg from "@assets/svgs/icon/solid/arrow-sm-down.svg";
export const SolidArrowSmDownSvg = withThemeColor(_SolidArrowSmDownSvg);

import _SolidArrowSmLeftSvg from "@assets/svgs/icon/solid/arrow-sm-left.svg";
export const SolidArrowSmLeftSvg = withThemeColor(_SolidArrowSmLeftSvg);

import _SolidArrowSmRightSvg from "@assets/svgs/icon/solid/arrow-sm-right.svg";
export const SolidArrowSmRightSvg = withThemeColor(_SolidArrowSmRightSvg);

import _SolidArrowSmUpSvg from "@assets/svgs/icon/solid/arrow-sm-up.svg";
export const SolidArrowSmUpSvg = withThemeColor(_SolidArrowSmUpSvg);

import _SolidArrowUpSvg from "@assets/svgs/icon/solid/arrow-up.svg";
export const SolidArrowUpSvg = withThemeColor(_SolidArrowUpSvg);

import _SolidArrowsExpandSvg from "@assets/svgs/icon/solid/arrows-expand.svg";
export const SolidArrowsExpandSvg = withThemeColor(_SolidArrowsExpandSvg);

import _SolidAtSymbolSvg from "@assets/svgs/icon/solid/at-symbol.svg";
export const SolidAtSymbolSvg = withThemeColor(_SolidAtSymbolSvg);

import _SolidBackspaceSvg from "@assets/svgs/icon/solid/backspace.svg";
export const SolidBackspaceSvg = withThemeColor(_SolidBackspaceSvg);

import _SolidBadgeCheckSvg from "@assets/svgs/icon/solid/badge-check.svg";
export const SolidBadgeCheckSvg = withThemeColor(_SolidBadgeCheckSvg);

import _SolidBanSvg from "@assets/svgs/icon/solid/ban.svg";
export const SolidBanSvg = withThemeColor(_SolidBanSvg);

import _SolidBeakerSvg from "@assets/svgs/icon/solid/beaker.svg";
export const SolidBeakerSvg = withThemeColor(_SolidBeakerSvg);

import _SolidBellSvg from "@assets/svgs/icon/solid/bell.svg";
export const SolidBellSvg = withThemeColor(_SolidBellSvg);

import _SolidBookOpenSvg from "@assets/svgs/icon/solid/book-open.svg";
export const SolidBookOpenSvg = withThemeColor(_SolidBookOpenSvg);

import _SolidBookmarkAltSvg from "@assets/svgs/icon/solid/bookmark-alt.svg";
export const SolidBookmarkAltSvg = withThemeColor(_SolidBookmarkAltSvg);

import _SolidBookmarkSvg from "@assets/svgs/icon/solid/bookmark.svg";
export const SolidBookmarkSvg = withThemeColor(_SolidBookmarkSvg);

import _SolidBriefcaseSvg from "@assets/svgs/icon/solid/briefcase.svg";
export const SolidBriefcaseSvg = withThemeColor(_SolidBriefcaseSvg);

import _SolidCakeSvg from "@assets/svgs/icon/solid/cake.svg";
export const SolidCakeSvg = withThemeColor(_SolidCakeSvg);

import _SolidCalendarSvg from "@assets/svgs/icon/solid/calendar.svg";
export const SolidCalendarSvg = withThemeColor(_SolidCalendarSvg);

import _SolidCameraSvg from "@assets/svgs/icon/solid/camera.svg";
export const SolidCameraSvg = withThemeColor(_SolidCameraSvg);

import _SolidCashSvg from "@assets/svgs/icon/solid/cash.svg";
export const SolidCashSvg = withThemeColor(_SolidCashSvg);

import _SolidChartBarSvg from "@assets/svgs/icon/solid/chart-bar.svg";
export const SolidChartBarSvg = withThemeColor(_SolidChartBarSvg);

import _SolidChartPieSvg from "@assets/svgs/icon/solid/chart-pie.svg";
export const SolidChartPieSvg = withThemeColor(_SolidChartPieSvg);

import _SolidChartSquareBarSvg from "@assets/svgs/icon/solid/chart-square-bar.svg";
export const SolidChartSquareBarSvg = withThemeColor(_SolidChartSquareBarSvg);

import _SolidChatAlt2Svg from "@assets/svgs/icon/solid/chat-alt-2.svg";
export const SolidChatAlt2Svg = withThemeColor(_SolidChatAlt2Svg);

import _SolidChatAltSvg from "@assets/svgs/icon/solid/chat-alt.svg";
export const SolidChatAltSvg = withThemeColor(_SolidChatAltSvg);

import _SolidChatSvg from "@assets/svgs/icon/solid/chat.svg";
export const SolidChatSvg = withThemeColor(_SolidChatSvg);

import _SolidCheckCircleSvg from "@assets/svgs/icon/solid/check-circle.svg";
export const SolidCheckCircleSvg = withThemeColor(_SolidCheckCircleSvg);

import _SolidCheckSvg from "@assets/svgs/icon/solid/check.svg";
export const SolidCheckSvg = withThemeColor(_SolidCheckSvg);

import _SolidCheveronDownSvg from "@assets/svgs/icon/solid/cheveron-down.svg";
export const SolidCheveronDownSvg = withThemeColor(_SolidCheveronDownSvg);

import _SolidCheveronLeftSvg from "@assets/svgs/icon/solid/cheveron-left.svg";
export const SolidCheveronLeftSvg = withThemeColor(_SolidCheveronLeftSvg);

import _SolidCheveronRightSvg from "@assets/svgs/icon/solid/cheveron-right.svg";
export const SolidCheveronRightSvg = withThemeColor(_SolidCheveronRightSvg);

import _SolidCheveronUpSvg from "@assets/svgs/icon/solid/cheveron-up.svg";
export const SolidCheveronUpSvg = withThemeColor(_SolidCheveronUpSvg);

import _SolidChevronDoubleDownSvg from "@assets/svgs/icon/solid/chevron-double-down.svg";
export const SolidChevronDoubleDownSvg = withThemeColor(_SolidChevronDoubleDownSvg);

import _SolidChevronDoubleLeftSvg from "@assets/svgs/icon/solid/chevron-double-left.svg";
export const SolidChevronDoubleLeftSvg = withThemeColor(_SolidChevronDoubleLeftSvg);

import _SolidChevronDoubleRightSvg from "@assets/svgs/icon/solid/chevron-double-right.svg";
export const SolidChevronDoubleRightSvg = withThemeColor(_SolidChevronDoubleRightSvg);

import _SolidChevronDoubleUpSvg from "@assets/svgs/icon/solid/chevron-double-up.svg";
export const SolidChevronDoubleUpSvg = withThemeColor(_SolidChevronDoubleUpSvg);

import _SolidChipSvg from "@assets/svgs/icon/solid/chip.svg";
export const SolidChipSvg = withThemeColor(_SolidChipSvg);

import _SolidClipboardCheckSvg from "@assets/svgs/icon/solid/clipboard-check.svg";
export const SolidClipboardCheckSvg = withThemeColor(_SolidClipboardCheckSvg);

import _SolidClipboardCopySvg from "@assets/svgs/icon/solid/clipboard-copy.svg";
export const SolidClipboardCopySvg = withThemeColor(_SolidClipboardCopySvg);

import _SolidClipboardListSvg from "@assets/svgs/icon/solid/clipboard-list.svg";
export const SolidClipboardListSvg = withThemeColor(_SolidClipboardListSvg);

import _SolidClockSvg from "@assets/svgs/icon/solid/clock.svg";
export const SolidClockSvg = withThemeColor(_SolidClockSvg);

import _SolidCloudDownloadSvg from "@assets/svgs/icon/solid/cloud-download.svg";
export const SolidCloudDownloadSvg = withThemeColor(_SolidCloudDownloadSvg);

import _SolidCloudUploadSvg from "@assets/svgs/icon/solid/cloud-upload.svg";
export const SolidCloudUploadSvg = withThemeColor(_SolidCloudUploadSvg);

import _SolidCloudSvg from "@assets/svgs/icon/solid/cloud.svg";
export const SolidCloudSvg = withThemeColor(_SolidCloudSvg);

import _SolidCodeSvg from "@assets/svgs/icon/solid/code.svg";
export const SolidCodeSvg = withThemeColor(_SolidCodeSvg);

import _SolidCogSvg from "@assets/svgs/icon/solid/cog.svg";
export const SolidCogSvg = withThemeColor(_SolidCogSvg);

import _SolidCollectionSvg from "@assets/svgs/icon/solid/collection.svg";
export const SolidCollectionSvg = withThemeColor(_SolidCollectionSvg);

import _SolidColorSwatchSvg from "@assets/svgs/icon/solid/color-swatch.svg";
export const SolidColorSwatchSvg = withThemeColor(_SolidColorSwatchSvg);

import _SolidCreditCardSvg from "@assets/svgs/icon/solid/credit-card.svg";
export const SolidCreditCardSvg = withThemeColor(_SolidCreditCardSvg);

import _SolidCubeTransparentSvg from "@assets/svgs/icon/solid/cube-transparent.svg";
export const SolidCubeTransparentSvg = withThemeColor(_SolidCubeTransparentSvg);

import _SolidCubeSvg from "@assets/svgs/icon/solid/cube.svg";
export const SolidCubeSvg = withThemeColor(_SolidCubeSvg);

import _SolidCurrencyBangladeshiSvg from "@assets/svgs/icon/solid/currency-bangladeshi.svg";
export const SolidCurrencyBangladeshiSvg = withThemeColor(_SolidCurrencyBangladeshiSvg);

import _SolidCurrencyDollarSvg from "@assets/svgs/icon/solid/currency-dollar.svg";
export const SolidCurrencyDollarSvg = withThemeColor(_SolidCurrencyDollarSvg);

import _SolidCurrencyEuroSvg from "@assets/svgs/icon/solid/currency-euro.svg";
export const SolidCurrencyEuroSvg = withThemeColor(_SolidCurrencyEuroSvg);

import _SolidCurrencyPoundSvg from "@assets/svgs/icon/solid/currency-pound.svg";
export const SolidCurrencyPoundSvg = withThemeColor(_SolidCurrencyPoundSvg);

import _SolidCurrencyRupeeSvg from "@assets/svgs/icon/solid/currency-rupee.svg";
export const SolidCurrencyRupeeSvg = withThemeColor(_SolidCurrencyRupeeSvg);

import _SolidCurrencyYenSvg from "@assets/svgs/icon/solid/currency-yen.svg";
export const SolidCurrencyYenSvg = withThemeColor(_SolidCurrencyYenSvg);

import _SolidCursorClickSvg from "@assets/svgs/icon/solid/cursor-click.svg";
export const SolidCursorClickSvg = withThemeColor(_SolidCursorClickSvg);

import _SolidDatabaseSvg from "@assets/svgs/icon/solid/database.svg";
export const SolidDatabaseSvg = withThemeColor(_SolidDatabaseSvg);

import _SolidDesktopComputerSvg from "@assets/svgs/icon/solid/desktop-computer.svg";
export const SolidDesktopComputerSvg = withThemeColor(_SolidDesktopComputerSvg);

import _SolidDeviceMobileSvg from "@assets/svgs/icon/solid/device-mobile.svg";
export const SolidDeviceMobileSvg = withThemeColor(_SolidDeviceMobileSvg);

import _SolidDocumentAddSvg from "@assets/svgs/icon/solid/document-add.svg";
export const SolidDocumentAddSvg = withThemeColor(_SolidDocumentAddSvg);

import _SolidDocumentDownloadSvg from "@assets/svgs/icon/solid/document-download.svg";
export const SolidDocumentDownloadSvg = withThemeColor(_SolidDocumentDownloadSvg);

import _SolidDocumentDuplicateSvg from "@assets/svgs/icon/solid/document-duplicate.svg";
export const SolidDocumentDuplicateSvg = withThemeColor(_SolidDocumentDuplicateSvg);

import _SolidDocumentRemoveSvg from "@assets/svgs/icon/solid/document-remove.svg";
export const SolidDocumentRemoveSvg = withThemeColor(_SolidDocumentRemoveSvg);

import _SolidDocumentReportSvg from "@assets/svgs/icon/solid/document-report.svg";
export const SolidDocumentReportSvg = withThemeColor(_SolidDocumentReportSvg);

import _SolidDocumentSearchSvg from "@assets/svgs/icon/solid/document-search.svg";
export const SolidDocumentSearchSvg = withThemeColor(_SolidDocumentSearchSvg);

import _SolidDocumentTextSvg from "@assets/svgs/icon/solid/document-text.svg";
export const SolidDocumentTextSvg = withThemeColor(_SolidDocumentTextSvg);

import _SolidDocumentSvg from "@assets/svgs/icon/solid/document.svg";
export const SolidDocumentSvg = withThemeColor(_SolidDocumentSvg);

import _SolidDotsCircleHorizontalSvg from "@assets/svgs/icon/solid/dots-circle-horizontal.svg";
export const SolidDotsCircleHorizontalSvg = withThemeColor(_SolidDotsCircleHorizontalSvg);

import _SolidDotsHorizontalSvg from "@assets/svgs/icon/solid/dots-horizontal.svg";
export const SolidDotsHorizontalSvg = withThemeColor(_SolidDotsHorizontalSvg);

import _SolidDotsVerticalSvg from "@assets/svgs/icon/solid/dots-vertical.svg";
export const SolidDotsVerticalSvg = withThemeColor(_SolidDotsVerticalSvg);

import _SolidDownload1Svg from "@assets/svgs/icon/solid/download-1.svg";
export const SolidDownload1Svg = withThemeColor(_SolidDownload1Svg);

import _SolidDownloadSvg from "@assets/svgs/icon/solid/download.svg";
export const SolidDownloadSvg = withThemeColor(_SolidDownloadSvg);

import _SolidDuplicateSvg from "@assets/svgs/icon/solid/duplicate.svg";
export const SolidDuplicateSvg = withThemeColor(_SolidDuplicateSvg);

import _SolidEmojiHappySvg from "@assets/svgs/icon/solid/emoji-happy.svg";
export const SolidEmojiHappySvg = withThemeColor(_SolidEmojiHappySvg);

import _SolidEmojiSadSvg from "@assets/svgs/icon/solid/emoji-sad.svg";
export const SolidEmojiSadSvg = withThemeColor(_SolidEmojiSadSvg);

import _SolidExclamationCircleSvg from "@assets/svgs/icon/solid/exclamation-circle.svg";
export const SolidExclamationCircleSvg = withThemeColor(_SolidExclamationCircleSvg);

import _SolidExclamationSvg from "@assets/svgs/icon/solid/exclamation.svg";
export const SolidExclamationSvg = withThemeColor(_SolidExclamationSvg);

import _SolidExternalLinkSvg from "@assets/svgs/icon/solid/external-link.svg";
export const SolidExternalLinkSvg = withThemeColor(_SolidExternalLinkSvg);

import _SolidEyeOffSvg from "@assets/svgs/icon/solid/eye-off.svg";
export const SolidEyeOffSvg = withThemeColor(_SolidEyeOffSvg);

import _SolidEyeSvg from "@assets/svgs/icon/solid/eye.svg";
export const SolidEyeSvg = withThemeColor(_SolidEyeSvg);

import _SolidFaceIdSvg from "@assets/svgs/icon/solid/face-id.svg";
export const SolidFaceIdSvg = withThemeColor(_SolidFaceIdSvg);

import _SolidFastForwardSvg from "@assets/svgs/icon/solid/fast-forward.svg";
export const SolidFastForwardSvg = withThemeColor(_SolidFastForwardSvg);

import _SolidFilmSvg from "@assets/svgs/icon/solid/film.svg";
export const SolidFilmSvg = withThemeColor(_SolidFilmSvg);

import _SolidFilterSvg from "@assets/svgs/icon/solid/filter.svg";
export const SolidFilterSvg = withThemeColor(_SolidFilterSvg);

import _SolidFingerPrintSvg from "@assets/svgs/icon/solid/finger-print.svg";
export const SolidFingerPrintSvg = withThemeColor(_SolidFingerPrintSvg);

import _SolidFireSvg from "@assets/svgs/icon/solid/fire.svg";
export const SolidFireSvg = withThemeColor(_SolidFireSvg);

import _SolidFlagSvg from "@assets/svgs/icon/solid/flag.svg";
export const SolidFlagSvg = withThemeColor(_SolidFlagSvg);

import _SolidFolderAddSvg from "@assets/svgs/icon/solid/folder-add.svg";
export const SolidFolderAddSvg = withThemeColor(_SolidFolderAddSvg);

import _SolidFolderDownloadSvg from "@assets/svgs/icon/solid/folder-download.svg";
export const SolidFolderDownloadSvg = withThemeColor(_SolidFolderDownloadSvg);

import _SolidFolderOpenSvg from "@assets/svgs/icon/solid/folder-open.svg";
export const SolidFolderOpenSvg = withThemeColor(_SolidFolderOpenSvg);

import _SolidFolderRemoveSvg from "@assets/svgs/icon/solid/folder-remove.svg";
export const SolidFolderRemoveSvg = withThemeColor(_SolidFolderRemoveSvg);

import _SolidFolderSvg from "@assets/svgs/icon/solid/folder.svg";
export const SolidFolderSvg = withThemeColor(_SolidFolderSvg);

import _SolidGiftSvg from "@assets/svgs/icon/solid/gift.svg";
export const SolidGiftSvg = withThemeColor(_SolidGiftSvg);

import _SolidGlobeAltSvg from "@assets/svgs/icon/solid/globe-alt.svg";
export const SolidGlobeAltSvg = withThemeColor(_SolidGlobeAltSvg);

import _SolidGlobeSvg from "@assets/svgs/icon/solid/globe.svg";
export const SolidGlobeSvg = withThemeColor(_SolidGlobeSvg);

import _SolidHandSvg from "@assets/svgs/icon/solid/hand.svg";
export const SolidHandSvg = withThemeColor(_SolidHandSvg);

import _SolidHashtagSvg from "@assets/svgs/icon/solid/hashtag.svg";
export const SolidHashtagSvg = withThemeColor(_SolidHashtagSvg);

import _SolidHeartSvg from "@assets/svgs/icon/solid/heart.svg";
export const SolidHeartSvg = withThemeColor(_SolidHeartSvg);

import _SolidHideGroupSvg from "@assets/svgs/icon/solid/hide-group.svg";
export const SolidHideGroupSvg = withThemeColor(_SolidHideGroupSvg);

import _SolidHomeSvg from "@assets/svgs/icon/solid/home.svg";
export const SolidHomeSvg = withThemeColor(_SolidHomeSvg);

import _SolidIconCurrencyDollarSvg from "@assets/svgs/icon/solid/icon-currency-dollar.svg";
export const SolidIconCurrencyDollarSvg = withThemeColor(_SolidIconCurrencyDollarSvg);

import _SolidIdentificationSvg from "@assets/svgs/icon/solid/identification.svg";
export const SolidIdentificationSvg = withThemeColor(_SolidIdentificationSvg);

import _SolidInboxInSvg from "@assets/svgs/icon/solid/inbox-in.svg";
export const SolidInboxInSvg = withThemeColor(_SolidInboxInSvg);

import _SolidInboxSvg from "@assets/svgs/icon/solid/inbox.svg";
export const SolidInboxSvg = withThemeColor(_SolidInboxSvg);

import _SolidInformationCircleSvg from "@assets/svgs/icon/solid/information-circle.svg";
export const SolidInformationCircleSvg = withThemeColor(_SolidInformationCircleSvg);

import _SolidKeySvg from "@assets/svgs/icon/solid/key.svg";
export const SolidKeySvg = withThemeColor(_SolidKeySvg);

import _SolidLightBulbSvg from "@assets/svgs/icon/solid/light-bulb.svg";
export const SolidLightBulbSvg = withThemeColor(_SolidLightBulbSvg);

import _SolidLightningBoltSvg from "@assets/svgs/icon/solid/lightning-bolt.svg";
export const SolidLightningBoltSvg = withThemeColor(_SolidLightningBoltSvg);

import _SolidLinkSvg from "@assets/svgs/icon/solid/link.svg";
export const SolidLinkSvg = withThemeColor(_SolidLinkSvg);

import _SolidLocationMarkerSvg from "@assets/svgs/icon/solid/location-marker.svg";
export const SolidLocationMarkerSvg = withThemeColor(_SolidLocationMarkerSvg);

import _SolidLockClosedSvg from "@assets/svgs/icon/solid/lock-closed.svg";
export const SolidLockClosedSvg = withThemeColor(_SolidLockClosedSvg);

import _SolidLockOpenSvg from "@assets/svgs/icon/solid/lock-open.svg";
export const SolidLockOpenSvg = withThemeColor(_SolidLockOpenSvg);

import _SolidLogout1Svg from "@assets/svgs/icon/solid/logout-1.svg";
export const SolidLogout1Svg = withThemeColor(_SolidLogout1Svg);

import _SolidLogoutSvg from "@assets/svgs/icon/solid/logout.svg";
export const SolidLogoutSvg = withThemeColor(_SolidLogoutSvg);

import _SolidMail1Svg from "@assets/svgs/icon/solid/mail-1.svg";
export const SolidMail1Svg = withThemeColor(_SolidMail1Svg);

import _SolidMailOpenSvg from "@assets/svgs/icon/solid/mail-open.svg";
export const SolidMailOpenSvg = withThemeColor(_SolidMailOpenSvg);

import _SolidMailSvg from "@assets/svgs/icon/solid/mail.svg";
export const SolidMailSvg = withThemeColor(_SolidMailSvg);

import _SolidMapSvg from "@assets/svgs/icon/solid/map.svg";
export const SolidMapSvg = withThemeColor(_SolidMapSvg);

import _SolidMdLibrarySvg from "@assets/svgs/icon/solid/md-library.svg";
export const SolidMdLibrarySvg = withThemeColor(_SolidMdLibrarySvg);

import _SolidMenuAlt1Svg from "@assets/svgs/icon/solid/menu-alt-1.svg";
export const SolidMenuAlt1Svg = withThemeColor(_SolidMenuAlt1Svg);

import _SolidMenuAlt2Svg from "@assets/svgs/icon/solid/menu-alt-2.svg";
export const SolidMenuAlt2Svg = withThemeColor(_SolidMenuAlt2Svg);

import _SolidMenuAlt3Svg from "@assets/svgs/icon/solid/menu-alt-3.svg";
export const SolidMenuAlt3Svg = withThemeColor(_SolidMenuAlt3Svg);

import _SolidMenuAlt4Svg from "@assets/svgs/icon/solid/menu-alt-4.svg";
export const SolidMenuAlt4Svg = withThemeColor(_SolidMenuAlt4Svg);

import _SolidMenuSvg from "@assets/svgs/icon/solid/menu.svg";
export const SolidMenuSvg = withThemeColor(_SolidMenuSvg);

import _SolidMicrophoneSvg from "@assets/svgs/icon/solid/microphone.svg";
export const SolidMicrophoneSvg = withThemeColor(_SolidMicrophoneSvg);

import _SolidMinusCircleSvg from "@assets/svgs/icon/solid/minus-circle.svg";
export const SolidMinusCircleSvg = withThemeColor(_SolidMinusCircleSvg);

import _SolidMinusSmSvg from "@assets/svgs/icon/solid/minus-sm.svg";
export const SolidMinusSmSvg = withThemeColor(_SolidMinusSmSvg);

import _SolidMinusSvg from "@assets/svgs/icon/solid/minus.svg";
export const SolidMinusSvg = withThemeColor(_SolidMinusSvg);

import _SolidMoonSvg from "@assets/svgs/icon/solid/moon.svg";
export const SolidMoonSvg = withThemeColor(_SolidMoonSvg);

import _SolidMusicNoteSvg from "@assets/svgs/icon/solid/music-note.svg";
export const SolidMusicNoteSvg = withThemeColor(_SolidMusicNoteSvg);

import _SolidNewspaperSvg from "@assets/svgs/icon/solid/newspaper.svg";
export const SolidNewspaperSvg = withThemeColor(_SolidNewspaperSvg);

import _SolidOfficeBuildingSvg from "@assets/svgs/icon/solid/office-building.svg";
export const SolidOfficeBuildingSvg = withThemeColor(_SolidOfficeBuildingSvg);

import _SolidPaperAirplaneSvg from "@assets/svgs/icon/solid/paper-airplane.svg";
export const SolidPaperAirplaneSvg = withThemeColor(_SolidPaperAirplaneSvg);

import _SolidPaperClipSvg from "@assets/svgs/icon/solid/paper-clip.svg";
export const SolidPaperClipSvg = withThemeColor(_SolidPaperClipSvg);

import _SolidPauseSvg from "@assets/svgs/icon/solid/pause.svg";
export const SolidPauseSvg = withThemeColor(_SolidPauseSvg);

import _SolidPencilAltSvg from "@assets/svgs/icon/solid/pencil-alt.svg";
export const SolidPencilAltSvg = withThemeColor(_SolidPencilAltSvg);

import _SolidPencilSvg from "@assets/svgs/icon/solid/pencil.svg";
export const SolidPencilSvg = withThemeColor(_SolidPencilSvg);

import _SolidPhoneIncomingSvg from "@assets/svgs/icon/solid/phone-incoming.svg";
export const SolidPhoneIncomingSvg = withThemeColor(_SolidPhoneIncomingSvg);

import _SolidPhoneMissedCallSvg from "@assets/svgs/icon/solid/phone-missed-call.svg";
export const SolidPhoneMissedCallSvg = withThemeColor(_SolidPhoneMissedCallSvg);

import _SolidPhoneOutgoingSvg from "@assets/svgs/icon/solid/phone-outgoing.svg";
export const SolidPhoneOutgoingSvg = withThemeColor(_SolidPhoneOutgoingSvg);

import _SolidPhoneSvg from "@assets/svgs/icon/solid/phone.svg";
export const SolidPhoneSvg = withThemeColor(_SolidPhoneSvg);

import _SolidPhotographSvg from "@assets/svgs/icon/solid/photograph.svg";
export const SolidPhotographSvg = withThemeColor(_SolidPhotographSvg);

import _SolidPinOffSvg from "@assets/svgs/icon/solid/pin-off.svg";
export const SolidPinOffSvg = withThemeColor(_SolidPinOffSvg);

import _SolidPlaySvg from "@assets/svgs/icon/solid/play.svg";
export const SolidPlaySvg = withThemeColor(_SolidPlaySvg);

import _SolidPlusCircleSvg from "@assets/svgs/icon/solid/plus-circle.svg";
export const SolidPlusCircleSvg = withThemeColor(_SolidPlusCircleSvg);

import _SolidPlusSmSvg from "@assets/svgs/icon/solid/plus-sm.svg";
export const SolidPlusSmSvg = withThemeColor(_SolidPlusSmSvg);

import _SolidPlusSvg from "@assets/svgs/icon/solid/plus.svg";
export const SolidPlusSvg = withThemeColor(_SolidPlusSvg);

import _SolidPresentationChartBarSvg from "@assets/svgs/icon/solid/presentation-chart-bar.svg";
export const SolidPresentationChartBarSvg = withThemeColor(_SolidPresentationChartBarSvg);

import _SolidPresentationChartLineSvg from "@assets/svgs/icon/solid/presentation-chart-line.svg";
export const SolidPresentationChartLineSvg = withThemeColor(_SolidPresentationChartLineSvg);

import _SolidPrinterSvg from "@assets/svgs/icon/solid/printer.svg";
export const SolidPrinterSvg = withThemeColor(_SolidPrinterSvg);

import _SolidPushPinSvg from "@assets/svgs/icon/solid/push-pin.svg";
export const SolidPushPinSvg = withThemeColor(_SolidPushPinSvg);

import _SolidPuzzleSvg from "@assets/svgs/icon/solid/puzzle.svg";
export const SolidPuzzleSvg = withThemeColor(_SolidPuzzleSvg);

import _SolidQrcodeSvg from "@assets/svgs/icon/solid/qrcode.svg";
export const SolidQrcodeSvg = withThemeColor(_SolidQrcodeSvg);

import _SolidQuestionMarkCircleSvg from "@assets/svgs/icon/solid/question-mark-circle.svg";
export const SolidQuestionMarkCircleSvg = withThemeColor(_SolidQuestionMarkCircleSvg);

import _SolidReceiptRefundSvg from "@assets/svgs/icon/solid/receipt-refund.svg";
export const SolidReceiptRefundSvg = withThemeColor(_SolidReceiptRefundSvg);

import _SolidReceiptTaxSvg from "@assets/svgs/icon/solid/receipt-tax.svg";
export const SolidReceiptTaxSvg = withThemeColor(_SolidReceiptTaxSvg);

import _SolidRefreshSvg from "@assets/svgs/icon/solid/refresh.svg";
export const SolidRefreshSvg = withThemeColor(_SolidRefreshSvg);

import _SolidReplySvg from "@assets/svgs/icon/solid/reply.svg";
export const SolidReplySvg = withThemeColor(_SolidReplySvg);

import _SolidRewindSvg from "@assets/svgs/icon/solid/rewind.svg";
export const SolidRewindSvg = withThemeColor(_SolidRewindSvg);

import _SolidRssSvg from "@assets/svgs/icon/solid/rss.svg";
export const SolidRssSvg = withThemeColor(_SolidRssSvg);

import _SolidSaveAsSvg from "@assets/svgs/icon/solid/save-as.svg";
export const SolidSaveAsSvg = withThemeColor(_SolidSaveAsSvg);

import _SolidSaveSvg from "@assets/svgs/icon/solid/save.svg";
export const SolidSaveSvg = withThemeColor(_SolidSaveSvg);

import _SolidScaleSvg from "@assets/svgs/icon/solid/scale.svg";
export const SolidScaleSvg = withThemeColor(_SolidScaleSvg);

import _SolidScissorsSvg from "@assets/svgs/icon/solid/scissors.svg";
export const SolidScissorsSvg = withThemeColor(_SolidScissorsSvg);

import _SolidSearchCircleSvg from "@assets/svgs/icon/solid/search-circle.svg";
export const SolidSearchCircleSvg = withThemeColor(_SolidSearchCircleSvg);

import _SolidSearchSvg from "@assets/svgs/icon/solid/search.svg";
export const SolidSearchSvg = withThemeColor(_SolidSearchSvg);

import _SolidSelectorSvg from "@assets/svgs/icon/solid/selector.svg";
export const SolidSelectorSvg = withThemeColor(_SolidSelectorSvg);

import _SolidServerSvg from "@assets/svgs/icon/solid/server.svg";
export const SolidServerSvg = withThemeColor(_SolidServerSvg);

import _SolidShareSvg from "@assets/svgs/icon/solid/share.svg";
export const SolidShareSvg = withThemeColor(_SolidShareSvg);

import _SolidShieldCheckSvg from "@assets/svgs/icon/solid/shield-check.svg";
export const SolidShieldCheckSvg = withThemeColor(_SolidShieldCheckSvg);

import _SolidShieldExclamationSvg from "@assets/svgs/icon/solid/shield-exclamation.svg";
export const SolidShieldExclamationSvg = withThemeColor(_SolidShieldExclamationSvg);

import _SolidShoppingBagSvg from "@assets/svgs/icon/solid/shopping-bag.svg";
export const SolidShoppingBagSvg = withThemeColor(_SolidShoppingBagSvg);

import _SolidSortAscendingSvg from "@assets/svgs/icon/solid/sort-ascending.svg";
export const SolidSortAscendingSvg = withThemeColor(_SolidSortAscendingSvg);

import _SolidSortDescendingSvg from "@assets/svgs/icon/solid/sort-descending.svg";
export const SolidSortDescendingSvg = withThemeColor(_SolidSortDescendingSvg);

import _SolidSparklesSvg from "@assets/svgs/icon/solid/sparkles.svg";
export const SolidSparklesSvg = withThemeColor(_SolidSparklesSvg);

import _SolidSpeakerphoneSvg from "@assets/svgs/icon/solid/speakerphone.svg";
export const SolidSpeakerphoneSvg = withThemeColor(_SolidSpeakerphoneSvg);

import _SolidStarSvg from "@assets/svgs/icon/solid/star.svg";
export const SolidStarSvg = withThemeColor(_SolidStarSvg);

import _SolidStatusOfflineSvg from "@assets/svgs/icon/solid/status-offline.svg";
export const SolidStatusOfflineSvg = withThemeColor(_SolidStatusOfflineSvg);

import _SolidStatusOnlineSvg from "@assets/svgs/icon/solid/status-online.svg";
export const SolidStatusOnlineSvg = withThemeColor(_SolidStatusOnlineSvg);

import _SolidStopSvg from "@assets/svgs/icon/solid/stop.svg";
export const SolidStopSvg = withThemeColor(_SolidStopSvg);

import _SolidSunSvg from "@assets/svgs/icon/solid/sun.svg";
export const SolidSunSvg = withThemeColor(_SolidSunSvg);

import _SolidSupportSvg from "@assets/svgs/icon/solid/support.svg";
export const SolidSupportSvg = withThemeColor(_SolidSupportSvg);

import _SolidSwitchHorizontalSvg from "@assets/svgs/icon/solid/switch-horizontal.svg";
export const SolidSwitchHorizontalSvg = withThemeColor(_SolidSwitchHorizontalSvg);

import _SolidSwitchVerticalSvg from "@assets/svgs/icon/solid/switch-vertical.svg";
export const SolidSwitchVerticalSvg = withThemeColor(_SolidSwitchVerticalSvg);

import _SolidTable1Svg from "@assets/svgs/icon/solid/table-1.svg";
export const SolidTable1Svg = withThemeColor(_SolidTable1Svg);

import _SolidTableSvg from "@assets/svgs/icon/solid/table.svg";
export const SolidTableSvg = withThemeColor(_SolidTableSvg);

import _SolidTagSvg from "@assets/svgs/icon/solid/tag.svg";
export const SolidTagSvg = withThemeColor(_SolidTagSvg);

import _SolidTemplateSvg from "@assets/svgs/icon/solid/template.svg";
export const SolidTemplateSvg = withThemeColor(_SolidTemplateSvg);

import _SolidTerminalSvg from "@assets/svgs/icon/solid/terminal.svg";
export const SolidTerminalSvg = withThemeColor(_SolidTerminalSvg);

import _SolidThemeSvg from "@assets/svgs/icon/solid/Theme.svg";
export const SolidThemeSvg = withThemeColor(_SolidThemeSvg);

import _SolidThumbDownSvg from "@assets/svgs/icon/solid/thumb-down.svg";
export const SolidThumbDownSvg = withThemeColor(_SolidThumbDownSvg);

import _SolidThumbUpSvg from "@assets/svgs/icon/solid/thumb-up.svg";
export const SolidThumbUpSvg = withThemeColor(_SolidThumbUpSvg);

import _SolidTicketSvg from "@assets/svgs/icon/solid/ticket.svg";
export const SolidTicketSvg = withThemeColor(_SolidTicketSvg);

import _SolidTranslateSvg from "@assets/svgs/icon/solid/translate.svg";
export const SolidTranslateSvg = withThemeColor(_SolidTranslateSvg);

import _SolidTrashSvg from "@assets/svgs/icon/solid/trash.svg";
export const SolidTrashSvg = withThemeColor(_SolidTrashSvg);

import _SolidTrendingDownSvg from "@assets/svgs/icon/solid/trending-down.svg";
export const SolidTrendingDownSvg = withThemeColor(_SolidTrendingDownSvg);

import _SolidTrendingUpSvg from "@assets/svgs/icon/solid/trending-up.svg";
export const SolidTrendingUpSvg = withThemeColor(_SolidTrendingUpSvg);

import _SolidTruckSvg from "@assets/svgs/icon/solid/truck.svg";
export const SolidTruckSvg = withThemeColor(_SolidTruckSvg);

import _SolidUploadSvg from "@assets/svgs/icon/solid/upload.svg";
export const SolidUploadSvg = withThemeColor(_SolidUploadSvg);

import _SolidUserAddSvg from "@assets/svgs/icon/solid/user-add.svg";
export const SolidUserAddSvg = withThemeColor(_SolidUserAddSvg);

import _SolidUserCircleSvg from "@assets/svgs/icon/solid/user-circle.svg";
export const SolidUserCircleSvg = withThemeColor(_SolidUserCircleSvg);

import _SolidUserGroupSvg from "@assets/svgs/icon/solid/user-group.svg";
export const SolidUserGroupSvg = withThemeColor(_SolidUserGroupSvg);

import _SolidUserRemoveSvg from "@assets/svgs/icon/solid/user-remove.svg";
export const SolidUserRemoveSvg = withThemeColor(_SolidUserRemoveSvg);

import _SolidUserSvg from "@assets/svgs/icon/solid/user.svg";
export const SolidUserSvg = withThemeColor(_SolidUserSvg);

import _SolidUsersSvg from "@assets/svgs/icon/solid/users.svg";
export const SolidUsersSvg = withThemeColor(_SolidUsersSvg);

import _SolidVariableSvg from "@assets/svgs/icon/solid/variable.svg";
export const SolidVariableSvg = withThemeColor(_SolidVariableSvg);

import _SolidVideoCameraSvg from "@assets/svgs/icon/solid/video-camera.svg";
export const SolidVideoCameraSvg = withThemeColor(_SolidVideoCameraSvg);

import _SolidViewBoardsSvg from "@assets/svgs/icon/solid/view-boards.svg";
export const SolidViewBoardsSvg = withThemeColor(_SolidViewBoardsSvg);

import _SolidViewGridAddSvg from "@assets/svgs/icon/solid/view-grid-add.svg";
export const SolidViewGridAddSvg = withThemeColor(_SolidViewGridAddSvg);

import _SolidViewGridSvg from "@assets/svgs/icon/solid/view-grid.svg";
export const SolidViewGridSvg = withThemeColor(_SolidViewGridSvg);

import _SolidViewListSvg from "@assets/svgs/icon/solid/view-list.svg";
export const SolidViewListSvg = withThemeColor(_SolidViewListSvg);

import _SolidVolumeOff1Svg from "@assets/svgs/icon/solid/volume-off-1.svg";
export const SolidVolumeOff1Svg = withThemeColor(_SolidVolumeOff1Svg);

import _SolidVolumeOffSvg from "@assets/svgs/icon/solid/volume-off.svg";
export const SolidVolumeOffSvg = withThemeColor(_SolidVolumeOffSvg);

import _SolidVolumeUp1Svg from "@assets/svgs/icon/solid/volume-up-1.svg";
export const SolidVolumeUp1Svg = withThemeColor(_SolidVolumeUp1Svg);

import _SolidVolumeUpSvg from "@assets/svgs/icon/solid/volume-up.svg";
export const SolidVolumeUpSvg = withThemeColor(_SolidVolumeUpSvg);

import _SolidWifiSvg from "@assets/svgs/icon/solid/wifi.svg";
export const SolidWifiSvg = withThemeColor(_SolidWifiSvg);

import _SolidXCircleSvg from "@assets/svgs/icon/solid/x-circle.svg";
export const SolidXCircleSvg = withThemeColor(_SolidXCircleSvg);

import _SolidXSvg from "@assets/svgs/icon/solid/x.svg";
export const SolidXSvg = withThemeColor(_SolidXSvg);

import _SolidZoomInSvg from "@assets/svgs/icon/solid/zoom-in.svg";
export const SolidZoomInSvg = withThemeColor(_SolidZoomInSvg);

import _SolidZoomOutSvg from "@assets/svgs/icon/solid/zoom-out.svg";
export const SolidZoomOutSvg = withThemeColor(_SolidZoomOutSvg);
