/**
 * Auto-generated by gen-assets.js
 * Source : /Users/ayobami/code/RiseAcademy/chatme/src/assets/svgs/assets
 * Alias  : @assets/svgs/assets
 * Assets : 1
 * Date   : 2026-08-09T22:55:35.180Z
 *
 * ⚠️  Do not edit this file manually — re-run gen-assets.js instead.
 */
export { default as LogoSvg } from "@assets/svgs/assets/logo.svg";
