/**
 * Auto-generated by gen-assets.js
 * Source : /Users/ayobami/code/RiseAcademy/chatme/src/assets/svgs/assets
 * Alias  : @assets/svgs/assets
 * Assets : 4
 * Date   : 2026-09-04T10:57:45.275Z
 *
 * ⚠️  Do not edit this file manually — re-run gen-assets.js instead.
 */
export { default as ChatBg1Svg } from "@assets/svgs/assets/chat-bg-1.svg";
export { default as ChatBg2Svg } from "@assets/svgs/assets/chat-bg-2.svg";
export { default as IllustrationCircleSvg } from "@assets/svgs/assets/illustration-circle.svg";
export { default as LogoSvg } from "@assets/svgs/assets/logo.svg";
