/**
 * Auto-generated by gen-assets.js
 * Source : /Users/ayobami/code/RiseAcademy/chatme/src/assets/svgs/assets
 * Alias  : @assets/svgs/assets
 * Assets : 2
 * Date   : 2026-08-15T15:24:08.297Z
 *
 * ⚠️  Do not edit this file manually — re-run gen-assets.js instead.
 */
export { default as IllustrationCircleSvg } from "@assets/svgs/assets/illustration-circle.svg";
export { default as LogoSvg } from "@assets/svgs/assets/logo.svg";
